# Generated by Django 5.1.2 on 2024-10-21 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_venta_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='usuario',
        ),
    ]
